### ISSUE TITLE
SIGSEGV when file is empty

### ISSUE THREAD

**Issue by dohnto** [garethr/kubetest#5]
## version

0.1.0

## what happened

We store secrets along with our other kubernetes manifests in git repository. Instead of secret, we put a dummy file which can be used as a template but it is commented so we can call `kubectl apply -f .`.
If I use kubetest on  all files, I receive a SIGSEGV.

## how to reproduce

```bash
$ cat secret.yaml 
#apiVersion: v1
#data:
#  password: dummy
#kind: Secret
#metadata:
#  name: database
#type: Opaque

$ cat tests/team.sky 
#// vim: set ft=python:
def test_for_team_label():
    if spec["kind"] == "Deployment":
        labels = spec["spec"]["template"]["metadata"]["labels"]
        assert_contains(labels, "team", "should indicate which team owns the deployment")

test_for_team_label()

$ kubetest secret.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x5a617d]

goroutine 1 [running]:
github.com/garethr/kubetest/vendor/github.com/garethr/skyhook/convert.MakeStringDict(0xc4200c8f60, 0x0, 0xc420115820, 0x5d1599)
	/home/travis/gopath/src/github.com/garethr/kubetest/vendor/github.com/garethr/skyhook/convert/conv.go:108 +0x11d
github.com/garethr/kubetest/vendor/github.com/garethr/skyhook.(*Skyhook).Run(0xc420115998, 0xc42008c5eb, 0x8, 0xc4200c8f60, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/garethr/kubetest/vendor/github.com/garethr/skyhook/skyhook.go:85 +0x40
github.com/garethr/kubetest/kubetest.Run(0xc4200bb180, 0x63, 0x263, 0x8b9abd, 0x5, 0x7ffea588ab06, 0xb, 0x1)
	/home/travis/gopath/src/github.com/garethr/kubetest/kubetest/kubetest.go:64 +0x8a3
github.com/garethr/kubetest/kubetest.Runs(0xc4200bb180, 0x63, 0x263, 0x8b9abd, 0x5, 0x7ffea588ab06, 0xb, 0x8bbd81)
	/home/travis/gopath/src/github.com/garethr/kubetest/kubetest/kubetest.go:109 +0x1aa
github.com/garethr/kubetest/cmd.glob..func1(0xaf20e0, 0xc420077820, 0x1, 0x1)
	/home/travis/gopath/src/github.com/garethr/kubetest/cmd/root.go:60 +0x226
github.com/garethr/kubetest/vendor/github.com/spf13/cobra.(*Command).execute(0xaf20e0, 0xc42009a070, 0x1, 0x1, 0xaf20e0, 0xc42009a070)
	/home/travis/gopath/src/github.com/garethr/kubetest/vendor/github.com/spf13/cobra/command.go:746 +0x2df
github.com/garethr/kubetest/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xaf20e0, 0xc4200a7220, 0x0, 0x0)
	/home/travis/gopath/src/github.com/garethr/kubetest/vendor/github.com/spf13/cobra/command.go:827 +0x349
github.com/garethr/kubetest/vendor/github.com/spf13/cobra.(*Command).Execute(0xaf20e0, 0x0, 0xc4200777a0)
	/home/travis/gopath/src/github.com/garethr/kubetest/vendor/github.com/spf13/cobra/command.go:780 +0x2b
github.com/garethr/kubetest/cmd.Execute()
	/home/travis/gopath/src/github.com/garethr/kubetest/cmd/root.go:75 +0x31
main.main()
	/home/travis/gopath/src/github.com/garethr/kubetest/main.go:6 +0x20

```

**Comment by hobbsh** [comment]
I am getting an identical panic using the example rc.yaml and two tests, so it may be more than just an empty file thing.

**Comment by garethr** [comment]
Thanks for reporting this. I've been able to recreate. Kubeval will detect empty files, but not correctly handle  files with all the content commented out. Looking for a fix.
